const MOTEL_FILES_FOLDER = 'MOTEL_FILES_FOLDER';
const CONTRACT_FILES_FOLDER = 'CONTRACT_FILES_FOLDER';
const BILL_FILES_FOLDER = 'BILL_FILES_FOLDER';
const RENTER_FILES_FOLDER = 'RENTER_FILES_FOLDER';
const PROBLEM_FILES_FOLDER = 'PROBLEM_FILES_FOLDER';
const ANOTHER_FILES_FOLDER = 'ANOTHER_FILES_FOLDER';
const MO_POST_FILES_FOLDER = 'MO_POST_FILES_FOLDER';
