const NEW_CONTRACT = 'NEW_CONTRACT'; // hợp đồng mới////
const CONTRACT_HAS_CHANGED = 'CONTRACT_HAS_CHANGED';

///

const NEW_HOST = 'NEW_HOST';
const NEW_BILL = 'NEW_BILL'; ////
const NEW_REPORT_PROBLEM = 'NEW_REPORT_PROBLEM'; ////
const REPORT_PROBLEM_DONE = 'REPORT_PROBLEM_DONE'; ////
const NEW_MO_POST = 'NEW_MO_POST'; ////
const NEW_ORDER_SERVICE = 'NEW_ORDER_SERVICE';
const CONFIRM_CONTRACT = 'CONFIRM_CONTRACT'; ////
const CONFIRM_CONTRACT_AND_DEPOSIT_PAID =
    'CONFIRM_CONTRACT_AND_DEPOSIT_PAID'; ////
const UNCONFIRMED_CONTRACT_BY_HOST = 'UNCONFIRMED_CONTRACT_BY_HOST'; /////
const POST_APPROVED = 'POST_APPROVED'; /////
const POST_CANCEL = 'POST_CANCEL';
const POST_APPROVED_AND_VERIFIED = 'POST_APPROVED_AND_VERIFIED'; /////
const CONTRACT_IS_ABOUT_TO_EXPIRE = 'CONTRACT_IS_ABOUT_TO_EXPIRE'; /////
const CONTRACT_EXPIRED = 'CONTRACT_EXPIRED'; //
const BILL_HAS_PAID = 'BILL_HAS_PAID'; //
const BILL_HAS_PAID_WAIT_HOST_CONFIRM = 'BILL_HAS_PAID_WAIT_HOST_CONFIRM';

///
const BILL_CANCEL_BY_RENTER = 'BILL_CANCEL_BY_RENTER'; /////
const RENTER_CONFIRMED = 'RENTER_CONFIRMED';
const BILL_NEED_PAID = 'BILL_NEED_PAID'; /////
const ORDER_SUCCESS = 'ORDER_SUCCESS';
const PAYMENT_DATE_MOTEL_IS_COMING = 'PAYMENT_DATE_MOTEL_IS_COMING';
const MATURITY_MOTEL = 'MATURITY_MOTEL';
const UNCONFIRMED_BILL_BY_HOST = 'UNCONFIRMED_BILL_BY_HOST';
const NEW_MESSAGE = "NEW_MESSAGE"; ////
const NEW_ORDER = "NEW_ORDER";
const TERMINATION_CONTRACT = 'TERMINATION_CONTRACT';

///
const CANCEL_ORDER = 'CANCEL_ORDER';

///
const CONTRACT_IS_ABOUT_TO_EXPIRE_MANAGE = 'CONTRACT_IS_ABOUT_TO_EXPIRE_MANAGE';
const CONTRACT_EXPIRED_MANAGE = 'CONTRACT_EXPIRED_MANAGE';
const NEW_REQUEST_WITHDRAWAL = 'NEW_REQUEST_WITHDRAWAL';
const APPROVED_REQUEST_WITHDRAWAL = 'APPROVED_REQUEST_WITHDRAWAL';
const BALANCE_CHANGE = 'BALANCE_CHANGE';
const NEW_RESERVATION = 'NEW_RESERVATION';
const NEW_FIND_FAST_MOTEL = 'NEW_FIND_FAST_MOTEL';
const NEW_REPORT_VIOLATION = 'NEW_REPORT_VIOLATION';
const PAYMENT_COLLABORATOR_MANAGE = 'PAYMENT_COLLABORATOR_MANAGE';
const CONFIRMED_COMMISSION_COLLABORATOR_FOR_HOST =
    'CONFIRMED_COMMISSION_COLLABORATOR_FOR_HOST'; //thông báo cho chủ nhà khi admin đã xác nhận chủ nhà thanh toán đủ
const CONFIRM_COMMISSION_PAYMENT_HOST_FOR_ADMIN =
    'CONFIRM_COMMISSION_PAYMENT_HOST_FOR_ADMIN'; //thông báo cho admin khi có thanh toán của chủ nhà cần duyệt.
const CONFIRM_COMMISSION_COLLABORATOR_FOR_ADMIN =
    'CONFIRM_COMMISSION_COLLABORATOR_FOR_ADMIN';
const NEW_MO_POST_FIND_MOTEL = "NEW_MO_POST_FIND_MOTEL";
const NEW_MO_POST_ROOMMATE = "NEW_MO_POST_ROOMMATE";
const NEW_CUSTOMER_POTENTIAL = "NEW_CUSTOMER_POTENTIAL";
const ADD_ROLE_MANAGE_TOWER = "ADD_ROLE_MANAGE_TOWER";
const ORDER_SHIPPING = "ORDER_SHIPPING";
