// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzhm-nPFM1OaNOgDIInWnPqXUhk4Afzng',
    appId: '1:37340311475:android:c641f9bd6ce833b78b65c6',
    messagingSenderId: '37340311475',
    projectId: 'rencity-2f771',
    storageBucket: 'rencity-2f771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUVOF6QBxuJFUJoTkSmdlE61bZxPY1jK4',
    appId: '1:37340311475:ios:0acb08aed20d78d98b65c6',
    messagingSenderId: '37340311475',
    projectId: 'rencity-2f771',
    storageBucket: 'rencity-2f771.appspot.com',
    iosClientId: '37340311475-trbsrp5i8affht8ihbqrut6c6kaatlof.apps.googleusercontent.com',
    iosBundleId: 'com.ikitech.rencity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUVOF6QBxuJFUJoTkSmdlE61bZxPY1jK4',
    appId: '1:37340311475:ios:97a5f14846d2bd5c8b65c6',
    messagingSenderId: '37340311475',
    projectId: 'rencity-2f771',
    storageBucket: 'rencity-2f771.appspot.com',
    iosClientId: '37340311475-2gqa80r6c445e5e2fbq7caarou9rv2i5.apps.googleusercontent.com',
    iosBundleId: 'com.ikitech.gohomy',
  );
}
